[package]
name = "rust_training_game_of_life"
version = "0.1.0"
authors = ["Damian Poddebniak <damian.poddebniak@fh-muenster.de>"]

[dependencies]
docopt          = "*"
rand            = "*"
rustc-serialize = "*"
